# Line icons (Phosphor, MIT) in one weight per mood.
# Downloads any missing SVGs into images/ph/<weight>/ and writes the icon rules into styles.css.
import re
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent
NAMES = [
    # features
    "palette", "device-mobile", "envelope-simple", "pencil-simple", "shield-check", "chat-circle-dots",
    # sample businesses
    "wrench", "hair-dryer", "scissors", "fork-knife", "tooth", "hammer", "broom", "barbell", "calculator", "bread",
    # blog covers
    "map-pin", "clipboard-text", "map-trifold", "scales", "star", "note-pencil", "buildings",
    # Google Maps plan levels
    "seal-check", "trend-up",
]
# Calm: regular · Transit and Tangy: bold · Sophisticated: thin
# (Filled icons were tried for Tangy but broke apart on shapes like the phone and envelope.)
WEIGHTS = {"regular": [""], "bold": [".theme-subway ", ".theme-blocks "], "thin": [".theme-wedding "]}
CDN = "https://cdn.jsdelivr.net/npm/@phosphor-icons/core@2/assets/{w}/{n}{s}.svg"

for w in WEIGHTS:
    d = HERE / "images" / "ph" / w
    d.mkdir(parents=True, exist_ok=True)
    for n in NAMES:
        f = d / f"{n}.svg"
        if not f.exists():
            s = "" if w == "regular" else f"-{w}"
            f.write_bytes(urllib.request.urlopen(CDN.format(w=w, n=n, s=s)).read())

rules = [".pi { display: inline-block; flex-shrink: 0; width: 1em; height: 1em; background: currentColor; -webkit-mask: center / contain no-repeat; mask: center / contain no-repeat; }"]
for w, scopes in WEIGHTS.items():
    rules += [", ".join(f"{s}.pi--{n}" for s in scopes) + f" {{ -webkit-mask-image: url(images/ph/{w}/{n}.svg); mask-image: url(images/ph/{w}/{n}.svg); }}" for n in NAMES]
block = "/* ICONS:START (generated by gen_icons.py) */\n" + "\n".join(rules) + "\n/* ICONS:END */"

css = (HERE / "styles.css").read_text()
if "/* ICONS:START" in css:
    css = re.sub(r"/\* ICONS:START.*?/\* ICONS:END \*/", lambda m: block, css, flags=re.S)
else:
    css = css.rstrip() + "\n\n" + block + "\n"
(HERE / "styles.css").write_text(css)
print(f"{len(NAMES)} icons x {len(WEIGHTS)} weights")
